name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true
    - name: Set up GCP credentials
      run: |
        cat <<EOL > gcp-key.json
        ${{ secrets.GCP_CREDENTIALS }}
        EOL
    - name: Authenticate with gcloud
      run: |
        gcloud auth activate-service-account ${{ secrets.GCP_EMAIL }} --key-file=gcp-key.json



    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M \
        --port 8000
